# Generated by Django 3.2.9 on 2021-12-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydb',
            name='hum',
        ),
    ]
