# Generated by Django 3.2.9 on 2021-12-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_mydb_hum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydb',
            name='hum',
            field=models.FloatField(null=True),
        ),
    ]
